services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ascort
      POSTGRES_PASSWORD: ascort
      POSTGRES_DB: ascortbali
    ports:
      - "5432:5432"
    volumes:
      - ascortbali_pg:/var/lib/postgresql/data
volumes:
  ascortbali_pg:
